ARG PYTHON_VERSION
ARG ALPINE_VERSION

FROM python:$PYTHON_VERSION-alpine$ALPINE_VERSION AS build-image

RUN apk update --no-cache                                                 \
    && apk add --no-cache                                                 \
    bash sudo postgresql-client libpq jpeg zlib libtool unixodbc freetds  \
    libffi czmq libxml2 libxslt openssl libwebp openjpeg ffmpeg ncdu htop \
    mailcap libmagic vips vips-tools

CMD ["/bin/bash"]
